change Sonar

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -133,7 +133,14 @@ jobs:
       - name: Build backend
         run: |
           cd back
-          mvn clean compile
+          mvn clean verify
+
+      - name: Validate jacoco report presence
+        run: |
+          if [ ! -f back/target/site/jacoco/jacoco.xml ]; then
+            echo "❌ Jacoco XML report not found"; exit 1;
+          fi
+
 
       - name: SonarQube Scan
         uses: SonarSource/sonarqube-scan-action@v5
